### ISSUE TITLE
runtime error running osg behavior space experiment

### ISSUE THREAD

**Issue by alee** [comses-education/chime-abm#2]
```
Run #1, RUNTIME ERROR: ITEM expected input to be a string or list but got the number 0 instead.
error while observer running ITEM                                                                                  
  called by procedure MOVE-HURRICANE                                                                               
  called by procedure GO                                                                                           
  called by procedure __EVALUATOR                                                                                  
org.nlogo.nvm.ArgumentTypeException: ITEM expected input to be a string or list but got the number 0 instead.
        at org.nlogo.prim._asm_proceduremovehurricane_setprocedurevariable_0.perform(:5)
        at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
        at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
        at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
        at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)                                        
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)       
        at scala.util.control.Exception$Catch.apply(Exception.scala:228)
        at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41) 
        at org.nlogo.job.JobThread.run(JobThread.scala:66)      
Run #2, RUNTIME ERROR: ITEM expected input to be a string or list but got the number 0 instead.
error while observer running ITEM                                                                                  
  called by procedure MOVE-HURRICANE                                                                               
  called by procedure GO                                                                                           
  called by procedure __EVALUATOR                                                                                  
org.nlogo.nvm.ArgumentTypeException: ITEM expected input to be a string or list but got the number 0 instead.
        at org.nlogo.prim._asm_proceduremovehurricane_setprocedurevariable_0.perform(:5)
        at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
        at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
        at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
        at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)                                        
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)       
        at scala.util.control.Exception$Catch.apply(Exception.scala:228)
        at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41) 
        at org.nlogo.job.JobThread.run(JobThread.scala:66)            
```

**Comment by seanbergin** [comment]
I believe that is an error created because the model isn't loading the hurricane information correctly. The likely cause is that the path to the hurricane info isn't correct.  I know we talked about this issue but I can't remember what we decided to do. There are 2 setup procedures, one that is for the ASU HPC and one that is for a regular computer. The locations of files for the HPC is hard coded, while the regular computer setup uses a path relative to the netlogo model.

**Comment by seanbergin** [comment]
After thinking about it a bit more - I changed it to setup-hpc in the behaviorspace file recently thinking that using setup was an error. It was probably on purpose. I'm trying out the behaviorspace experiment now to see if I can hunt down any other bugs.

**Comment by seanbergin** [comment]
The behaviorspace file is updated and I may have found and fixed the root of the problem. The code was written to manually stop the model at a specific step or tick if it was being run on a HPC. But, we were using setup, not setup-hpc, so the model did not know it was on an HPC. Long story short, got rid of that condition for the model to stop.
